export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    ME: "/auth/me",
    REFRESH_TOKEN: "/auth/refresh-token",
    CHANGE_PASSWORD: "/auth/change-password",
    FORGET_PASSWORD: "/auth/forget-password",
    RESET_PASSWORD: "/auth/reset-password",
    VERIFY_EMAIL: "/auth/verify-email",
    RESEND_OTP: "/auth/resend-otp",
  },
  IDEAS: {
    ALL: "/ideas",
    DETAIL: (id: string) => `/ideas/${id}`,
    CREATE: "/ideas",
    UPDATE: (id: string) => `/ideas/${id}`,
    DELETE: (id: string) => `/ideas/${id}`,
    SUBMIT: (id: string) => `/ideas/${id}/submit`,
    MY_IDEAS: "/ideas/my-ideas",
    FEATURED: "/ideas/featured",
    TESTIMONIALS: "/ideas/testimonials",
    BY_CATEGORY: (categoryId: string) => `/ideas/category/${categoryId}`,
    RELATED: (id: string, limit: number = 3) =>
      `/ideas/${id}/related?limit=${limit}`,
  },
  VOTES: {
    VOTE: "/votes",
    REMOVE: (ideaId: string) => `/votes/${ideaId}`,
    USER_VOTE: (ideaId: string) => `/votes/${ideaId}`,
    MY_VOTES: "/votes/me/all",
  },
  COMMENTS: {
    BY_IDEA: (ideaId: string) => `/comments?ideaId=${ideaId}`,
    CREATE: "/comments",
    UPDATE: (id: string) => `/comments/${id}`,
    DELETE: (id: string) => `/comments/${id}`,
    HARD_DELETE: (id: string) => `/comments/${id}/permanent`,
  },
  BOOKMARKS: {
    TOGGLE: "/bookmarks",
    MY_BOOKMARKS: "/bookmarks/me",
    CHECK: (ideaId: string) => `/bookmarks/check/${ideaId}`,
  },
  CATEGORIES: {
    ALL: "/categories",
    CREATE: "/categories",
    UPDATE: (id: string) => `/categories/${id}`,
    DELETE: (id: string) => `/categories/${id}`,
  },
  PAYMENTS: {
    CHECKOUT: "/payments/checkout",
    MY_PAYMENTS: "/payments/me",
    VERIFY: (ideaId: string) => `/payments/verify/${ideaId}`,
  },
  NEWSLETTER: {
    SUBSCRIBE: "/newsletter/subscribe",
    UNSUBSCRIBE: "/newsletter/unsubscribe",
    SUBSCRIBERS: "/newsletter",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    MEMBERS: "/admin/members",
    MEMBER: (id: string) => `/admin/members/${id}`,
    IDEAS_ALL: "/admin/ideas/all",
    EXPORT_USERS: "/admin/export/users",
    EXPORT_IDEAS: "/admin/export/ideas",
    BULK_APPROVE: "/admin/ideas/bulk/approve",
    BULK_REJECT: "/admin/ideas/bulk/reject",
  },
  UPLOADS: {
    IDEA_IMAGES: (ideaId: string) => `/uploads/ideas/images?ideaId=${ideaId}`,
    DELETE_IMAGE: (ideaId: string, publicId: string) =>
      `/uploads/ideas/${ideaId}/images/${publicId}`,
    PROFILE_IMAGE: "/uploads/profile/image",
  },
  NOTIFICATIONS: {
    MY_NOTIFICATIONS: "/notifications/me",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
  REPORTS: {
    CREATE: "/reports",
    ALL: "/reports",
    UPDATE_STATUS: (id: string) => `/reports/${id}`,
  },
  ACTIVITIES: {
    MY_ACTIVITIES: "/activities/me",
    ALL_ACTIVITIES: "/activities",
  },
  AUDIT_LOGS: {
    ALL: "/audit-logs",
  },
  SETTINGS: {
    PUBLIC: "/settings/public",
    ALL: "/settings",
    BY_KEY: (key: string) => `/settings/${key}`,
    CREATE: "/settings",
    UPDATE: (key: string) => `/settings/${key}`,
    DELETE: (key: string) => `/settings/${key}`,
  },
  BLOG: {
    ALL: "/blogs",
    BY_SLUG: (slug: string) => `/blogs/${slug}`,
    RELATED: (id: string, limit: number = 3) =>
      `/blogs/${id}/related?limit=${limit}`,
    CREATE: "/blogs",
    UPDATE: (id: string) => `/blogs/${id}`,
    DELETE: (id: string) => `/blogs/${id}`,
    PUBLISH: (id: string) => `/blogs/${id}/publish`,
    COMMENTS: (blogId: string) => `/blogs/${blogId}/comments`,
    CREATE_COMMENT: "/blogs/comments",
    DELETE_COMMENT: (commentId: string) => `/blogs/comments/${commentId}`,
    LIKE: (blogId: string) => `/blogs/${blogId}/like`,
    CATEGORIES: "/blogs/categories/all",
    TAGS: "/blogs/tags/all",
  },
} as const;
